### ISSUE TITLE
Open Source Release

### ISSUE THREAD

**Issue by terraboops** [grafana/nethax#10]
Ensure none of the following is present in the repo or history:

```[tasklist]
### Tasks
- [x] Rename project to nethax
- [x] Double check repo and history for confidential information
- [x] Ensure there are no links to internal repos/issues/etc
- [x] Ensure there are no customer names
- [x] Suitability of code comments
- [x] Avoid internal references, names/emails
- [x] Profanity
```
