### ISSUE TITLE
Replace use of netcat with a new nethax probe

### ISSUE THREAD

**Issue by terraboops** [grafana/nethax#27]
To make tests faster, it would be better if nethax downloaded a small probe container rather than using the netshoot debug container.

```[tasklist]
### Tasks
- [x] Split the project up to support two binaries
- [x] Build a skeleton for the nethax-probe binary
- [x] Probe binary should: take flag arguments, make TCP connection based on flags, report outcome of connection
- [ ] Make a docker container for probe binary
- [ ] Replace usage of netcat in nethax with nethax-probe
```

**Comment by terraboops** [comment]
Closed by #35
